{"name": "test_validlogin", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <tests.home.login_test.LoginTest testMethod=test_validlogin>\n\n    @pytest.mark.run(order=2)\n    def test_validlogin(self):\n        self.lp.login(\"test@email.com\", \"abcabc\")\n        self.lp.logout()\n        result1 = self.lp.verifyTitle()\n        self.ts.mark(result1, \"title not correct\")\n        result2 = self.lp.verifyloginsuccessful()\n>       self.ts.markfinal(\"test_validlogin\", result2, \"login succussful\")\n\ntests\\home\\login_test.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilitis.teststatus.TestStatus object at 0x0495C230>, testname = 'test_validlogin', result = False, resultmessage = 'login succussful'\n\n    def markfinal(self,testname, result, resultmessage):\n        self.setresult(result, resultmessage)\n        if 'FAIL' in self.resultlist:\n            self.log.error(\"### test failed\")\n            self.resultlist.clear()\n>           assert True ==False\nE           AssertionError\n\nutilitis\\teststatus.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "f73a30d5-e535-4f89-89cf-5d019cfa1b9a-attachment.txt", "type": "text/plain"}], "start": 1564129243774, "stop": 1564129300359, "uuid": "f9b6081f-2ccd-4629-8cab-887b4b0ce5b1", "historyId": "07917985b2a4bfebfa897af40f0bf3ff", "fullName": "tests.home.login_test.LoginTest#test_validlogin", "labels": [{"name": "parentSuite", "value": "tests.home"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "LAPTOP-FBAQ7RAA"}, {"name": "thread", "value": "14664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.home.login_test"}]}